In [2]:
for i in [2,3,6,8]:
    print(i+1)

3
4
7
9


In [6]:
i=1
while i<4:
    print(i)
    i+=1

1
2
3


In [7]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
t = tuple(range(10))
t

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

In [3]:
# importar la libreria
import numpy as np

In [4]:
Npa = np.array(range(10))
Npa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
Np_cero = np.zeros(10) # los crea tipo float
Np_cero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
Np_cero_int=np.zeros(10,dtype=int) #los crea tipo entero
Np_cero_int

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
Np_uno = np.ones(10)
Np_uno


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
Np_relleno = np.full(10,256)
Np_relleno

array([256, 256, 256, 256, 256, 256, 256, 256, 256, 256])

In [18]:
Np_ones_int=np.ones(10,dtype=int) #los crea tipo entero
Np_ones_int

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
Np_rango=np.full(5,11)
Np_rango

array([11, 11, 11, 11, 11])

In [13]:
Np_rango = np.arange(10)
Np_rango

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
Np_random_dimensiones=np.random.randint(20, size=(3,4))
Np_random_dimensiones

array([[18, 18, 11,  6],
       [ 9, 11,  5, 17],
       [ 6, 18, 17, 14]])

In [19]:
Np_cero.ndim

1

In [20]:
Np_random_dimensiones.ndim

2

In [23]:
Np_random_dimensiones.shape

(3, 4, 3)

In [26]:
Np_random_dimensiones.size

36

In [27]:
Np_random_dimensiones.ndim

3

In [28]:
Np_random_dimensiones.shape

(3, 4, 3)

In [22]:
Np_random_dimensiones=np.random.randint(10, size=(3,4,3))
Np_random_dimensiones

array([[[8, 0, 8],
        [0, 4, 6],
        [4, 5, 6],
        [7, 4, 5]],

       [[5, 3, 0],
        [6, 4, 4],
        [6, 1, 6],
        [4, 0, 2]],

       [[9, 8, 6],
        [8, 5, 6],
        [2, 8, 1],
        [8, 0, 9]]])

In [32]:
print(Np_random_dimensiones.size)
print(Np_random_dimensiones.ndim)
print(Np_random_dimensiones.shape)
print(Np_random_dimensiones)
print(Np_random_dimensiones.dtype)
print(Np_random_dimensiones.itemsize)
print(Np_random_dimensiones.nbytes)

36
3
(3, 4, 3)
[[[3 7 5]
  [3 2 1]
  [5 9 6]
  [2 7 6]]

 [[2 2 9]
  [4 3 4]
  [9 7 0]
  [7 1 9]]

 [[4 4 7]
  [4 7 6]
  [8 5 7]
  [3 6 3]]]
int32
4
144


In [36]:
Np_2_dim = np.random.randint(10, size=(3,3,3))
Np_2_dim

array([[[1, 4, 2],
        [1, 0, 4],
        [0, 6, 9]],

       [[2, 8, 6],
        [8, 8, 9],
        [3, 4, 2]],

       [[6, 6, 0],
        [8, 5, 6],
        [9, 2, 2]]])

In [29]:
Np_cero.dtype

dtype('float64')

In [32]:
Np_cero_int.dtype


dtype('int32')

In [33]:
Np_random_dimensiones.itemsize


4

In [37]:
rango=range(1,11)
Np_diez_numeros=np.array(rango)
Np_diez_numeros

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
Np_2_dim[0,0,1]

4

In [45]:
Np_diez_numeros= np.array(range(10))
Np_diez_numeros


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
Np_diez_numeros[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [51]:

Ajedrez_64 = np.arange(1,65).reshape(8,8)
Ajedrez_64

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [53]:
UnoSeisCuatro= np.arange(1,65)
UnoSeisCuatro

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [54]:
UnoSeisCuatro.reshape(8,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [4]:
Array_1=np.random.randint(10,size=5)
Array_1

array([5, 2, 5, 7, 6])

In [5]:
Array_2=np.random.randint(10,size=5)
Array_2

array([2, 8, 2, 9, 4])

In [58]:
Array_conc=np.concatenate([Array_1,Array_2])
Array_conc

array([0, 8, 1, 5, 0, 0, 0, 8, 8, 8])

In [61]:
Array_extra=np.array([Array_1,Array_2])
Array_extra

array([[0, 8, 1, 5, 0],
       [0, 0, 8, 8, 8]])

In [62]:
Array_v=np.vstack([Array_1,Array_2])
Array_v

array([[0, 8, 1, 5, 0],
       [0, 0, 8, 8, 8]])

In [67]:
Array_aleatorio = np.random.randint(1000, size=10)
print(Array_aleatorio)
suma = 0
for i in Array_aleatorio:
    suma += i
promedio = suma/np.size(Array_aleatorio)
promedio

[555 461 891 860 169 194 735 662 765 110]


540.2

In [73]:
Array_aleatorio_1 = np.random.randint(1000, size=10)
print(Array_aleatorio_1)


[980 936 603 275 848 109 180 715 376 669]


In [74]:
%%time
Array_aleatorio_1.mean()

CPU times: total: 0 ns
Wall time: 0 ns


569.1

In [76]:
suma = 0
for i in Array_aleatorio_1:
    suma += i
promedio = suma/np.size(Array_aleatorio_1)
promedio


569.1

In [77]:
Array_1+Array_2

array([ 0,  8,  9, 13,  8])

In [78]:
np.add(Array_1,Array_2)

array([ 0,  8,  9, 13,  8])

In [79]:
Array_1+100

array([100, 108, 101, 105, 100])

In [87]:
Array_aleatorio_entrega = np.random.randint(100, size=100)
print(Array_aleatorio_entrega)
print ("Mediana serie: ", np.median(Array_aleatorio_entrega))
print("Media serie: ",np.mean(Array_aleatorio_entrega))

[27 46  6 33 43  4 90 52 74 92 39 13 21 20  6 83 64 35 50 79 54 40 19 83
 72  3 32 68 39 62 66 56 68 73 25 39 69 96 14 48  2 78  0 51 20 82 23 46
 63 26 68 76 97 49 17 10 61 49 76 14  0 78  8 85 17 99 68  4  1 58 48 30
 81 45  3 93  6 25 28 84 26  9 78 57 93 90 75 17  5 99 21 11 51 12 75 28
 40 58  8 95]
Mediana serie:  47.0
Media serie:  46.2


In [88]:
sueldos =np.array([1,1,1,1,2,4,5])
sueldos

array([1, 1, 1, 1, 2, 4, 5])

In [38]:
rango=range(1,11)
Np_diez_numeros=np.array(rango)
Np_diez_numeros

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
Np_diez_numeros[0]

1

In [40]:
Np_diez_numeros[4]

5

In [41]:
Np_diez_numeros[-1]

10

In [42]:
Np_diez_numeros[-3]

8

In [43]:
Np_random_dimensiones=np.random.randint(20, size=(3,4))
Np_random_dimensiones

array([[18,  3, 17,  8],
       [ 2, 15, 19,  0],
       [ 8,  3,  9,  4]])

In [44]:
Np_random_dimensiones

array([[18,  3, 17,  8],
       [ 2, 15, 19,  0],
       [ 8,  3,  9,  4]])

In [45]:
Np_random_dimensiones[2,1]

3

In [47]:
Np_random_dimensiones[1,1]

15

In [49]:
Np_random_dimensiones[2,3]

4

In [50]:
Np_random_dimensiones[1,2]

19

In [67]:
Np_random_otro=np.random.randint(10, size=(2,3,4))
Np_random_otro

array([[[0, 1, 2, 0],
        [4, 1, 6, 4],
        [6, 6, 9, 9]],

       [[7, 1, 6, 9],
        [8, 1, 2, 5],
        [8, 6, 8, 3]]])

In [53]:
Np_random_otro[1,0,1]

8

In [55]:
Np_random_otro[0,0,2]

4

In [58]:
Np_diez_numeros

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
Np_diez_numeros[:4]


array([1, 2, 3, 4])

In [61]:
Np_diez_numeros[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [62]:
Np_diez_numeros[4:7]

array([5, 6, 7])

In [63]:
Np_diez_numeros[3:7]

array([4, 5, 6, 7])

In [64]:
Np_diez_numeros[::2]

array([1, 3, 5, 7, 9])

In [65]:
Np_diez_numeros[::-2]

array([10,  8,  6,  4,  2])

In [69]:
Np_random_otro[1,]

array([[7, 1, 6, 9],
       [8, 1, 2, 5],
       [8, 6, 8, 3]])

In [70]:
Np_random_otro

array([[[0, 1, 2, 0],
        [4, 1, 6, 4],
        [6, 6, 9, 9]],

       [[7, 1, 6, 9],
        [8, 1, 2, 5],
        [8, 6, 8, 3]]])

In [71]:
Np_random_otro[:1,:1] #no entiendo

array([[[0, 1, 2, 0]]])

In [73]:
Np_random_otro[1,1] #no entiendo


array([8, 1, 2, 5])

In [81]:
Np_ajedrez_64 = np.arange(1,65).reshape(8,8)
Np_ajedrez_64

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [2]:
Array_1=np.random.randint(10,size=5)
Array_1


NameError: name 'np' is not defined

In [84]:
Array_2=np.random.randint(10,size=5)
Array_2

array([3, 5, 9, 3, 3])

In [86]:
Array_concat_12=np.concatenate([Array_1,Array_2])
Array_concat_12

array([5, 0, 1, 7, 9, 3, 5, 9, 3, 3])

In [88]:
#Concatenacion
#vstack
Array_extra=np.array([[10],[20]])
Array_extra

array([[10],
       [20]])

In [89]:
Array_extra[0,0]

10

In [90]:
Array_extra[1,0]

20

In [92]:
Array_v_apilados=np.vstack([Array_1,Array_2])
Array_v_apilados

array([[5, 0, 1, 7, 9],
       [3, 5, 9, 3, 3]])

In [93]:
Array_v_apilados21=np.vstack([Array_2,Array_1])
Array_v_apilados21

array([[3, 5, 9, 3, 3],
       [5, 0, 1, 7, 9]])

In [95]:
Array_h_apilados_12=np.hstack([Array_1,Array_2])
Array_h_apilados_12


array([5, 0, 1, 7, 9, 3, 5, 9, 3, 3])

In [96]:
Array_h_apilados_21=np.hstack([Array_2,Array_1])
Array_h_apilados_21

array([3, 5, 9, 3, 3, 5, 0, 1, 7, 9])

In [100]:
#splitting
Array_h_apilados_12
Array_h_apilados_12_partido = np.split(Array_h_apilados_12,[2])
Array_h_apilados_12_partido 

[array([5, 0]), array([1, 7, 9, 3, 5, 9, 3, 3])]

In [101]:
Array_h_apilados_12_partido = np.split(Array_h_apilados_12,[4])
Array_h_apilados_12_partido 

[array([5, 0, 1, 7]), array([9, 3, 5, 9, 3, 3])]

In [104]:
#split
Array_h_apilados_12_partido = np.split(Array_h_apilados_12,[2,5,7])
Array_h_apilados_12_partido
Parte_1,Parte_2,Parte_3,Parte_4=Array_h_apilados_12_partido
Parte_1,Parte_2,Parte_3,Parte_4

(array([5, 0]), array([1, 7, 9]), array([3, 5]), array([9, 3, 3]))

In [105]:
#hsplit
Np_ajedrez_64
Ajedrez_split_h=np.hsplit(Np_ajedrez_64,[4])
Ajedrez_split_h

[array([[ 1,  2,  3,  4],
        [ 9, 10, 11, 12],
        [17, 18, 19, 20],
        [25, 26, 27, 28],
        [33, 34, 35, 36],
        [41, 42, 43, 44],
        [49, 50, 51, 52],
        [57, 58, 59, 60]]),
 array([[ 5,  6,  7,  8],
        [13, 14, 15, 16],
        [21, 22, 23, 24],
        [29, 30, 31, 32],
        [37, 38, 39, 40],
        [45, 46, 47, 48],
        [53, 54, 55, 56],
        [61, 62, 63, 64]])]

In [106]:
Ajedrez_split_h=np.hsplit(Np_ajedrez_64,[2])
Ajedrez_split_h

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26],
        [33, 34],
        [41, 42],
        [49, 50],
        [57, 58]]),
 array([[ 3,  4,  5,  6,  7,  8],
        [11, 12, 13, 14, 15, 16],
        [19, 20, 21, 22, 23, 24],
        [27, 28, 29, 30, 31, 32],
        [35, 36, 37, 38, 39, 40],
        [43, 44, 45, 46, 47, 48],
        [51, 52, 53, 54, 55, 56],
        [59, 60, 61, 62, 63, 64]])]

In [107]:
Ajedrez_split_h=np.hsplit(Np_ajedrez_64,[2,4])
Ajedrez_split_h

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26],
        [33, 34],
        [41, 42],
        [49, 50],
        [57, 58]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28],
        [35, 36],
        [43, 44],
        [51, 52],
        [59, 60]]),
 array([[ 5,  6,  7,  8],
        [13, 14, 15, 16],
        [21, 22, 23, 24],
        [29, 30, 31, 32],
        [37, 38, 39, 40],
        [45, 46, 47, 48],
        [53, 54, 55, 56],
        [61, 62, 63, 64]])]

In [109]:
#array split vertical
Ajedrez_split_v=np.vsplit(Np_ajedrez_64,[4])
Ajedrez_split_v

[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32]]),
 array([[33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55, 56],
        [57, 58, 59, 60, 61, 62, 63, 64]])]

In [110]:
Ajedrez_split_v=np.vsplit(Np_ajedrez_64,[2,4])
Ajedrez_split_v

[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16]]),
 array([[17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32]]),
 array([[33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55, 56],
        [57, 58, 59, 60, 61, 62, 63, 64]])]

In [118]:
#Ejemplo calculo de promedio de un array
Array_aleatorio=np.random.randint(10,size=10)
Array_aleatorio


array([3, 7, 3, 2, 8, 1, 7, 3, 9, 5])

In [119]:
#Aca con funcion
print(Array_aleatorio)
suma=0
for i in Array_aleatorio:
    suma+=i
promedio = suma/np.size(Array_aleatorio)
promedio

[3 7 3 2 8 1 7 3 9 5]


4.8

In [121]:
#Aca con simplificadas
print( "Este es la suma del array: ",Array_aleatorio.sum())
print( "Este es el promedio del array: ",Array_aleatorio.mean())
print( "Este es el valor maximo del array: ",Array_aleatorio.max())
print( "Este es la mediana del array: ",np.median(Array_aleatorio))
print( "Este es el desvio standar del array: ",np.std(Array_aleatorio))
print( "Este es la varianza del array: ",np.var(Array_aleatorio))

Este es la suma del array:  48
Este es el promedio del array:  4.8
Este es el valor maximo del array:  9
Este es la mediana del array:  4.0
Este es el desvio standar del array:  2.638181191654584
Este es la varianza del array:  6.960000000000001


In [6]:
#Operaciones vectorizadas ó ufuncs
Array_1,Array_2


(array([5, 2, 5, 7, 6]), array([2, 8, 2, 9, 4]))

In [7]:
Array_1+5

array([10,  7, 10, 12, 11])

In [8]:
Array_1+Array_2

array([ 7, 10,  7, 16, 10])

In [9]:
np.add(Array_1,Array_2)

array([ 7, 10,  7, 16, 10])

In [10]:
#Producto vectorial
np.matmul(Array_1,Array_2)

123

In [18]:
#tp Arrays+Heredia #Ejercicio 1
Array_aleatorio_de_100=np.random.randint(888, size=100)
print(Array_aleatorio_de_100)
print("La mediana del array es: ",np.median(Array_aleatorio_de_100))

[824 122 843 537 116 858 515 497 106 305  45 143 625 208 474 429 521  68
 735 243 165 405 787 315 470 628 810 670 459 613  29 239 337 806 804 551
 359 156 657 670  26 824 649 845 465 280 539 722 845 858 164 746 777 133
 238 310  80 510 385 521  12 314 158 113 762 870 120 325 209 711 238 699
 862 181 385 725 433  50 502 299 292 322 432 179 805 155 638 858 496 773
 805 420 282 365 372 652  90  95 451 446]
La mediana del array es:  439.5


In [16]:
#tp Arrays+Heredia #Ejecicio 2
def factorizar(x): #definimos funcion
    fac=1
    for i in range(1,(x+1)): #Operación de la función
        fac*=i
    return(fac)
    

factorizar(3) #prueba con un número cualquiera

6

In [17]:
#tp Arrays+Heredia #Ejecicio 2
def SumarNumerosEntre(x,y): #definimos las función
    sum=0
    if y>x: #condicional para asegurar la operación
        for i in range(x,(y+1)):
            sum+=i
        return(sum)
    else: #mensaje en caso de error
        return("Segundo argumento debe ser mayor al primero")

SumarNumerosEntre(0,3) #prueba con dos numeros

6

In [22]:
#Array sueldos
Array_Sueldos_Openqube_Feb_2020 = [
    53000,
    79000,
    160000,
    130000,
    140000,
    54000,
    75000,
    45000,
    105000,
    47000,
    36800,
    93735,
    70000,
    102000,
    102000,
    100000,
    140000,
    88000,
    125000,
    75000,
    87000,
    36874,
    100000,
    47945,
    80000,
    140000,
    260000,
    36000,
    89000,
    94000,
    123000,
    160000,
    56000,
    63300,
    268000,
    38500,
    100000,
    196000,
    100000,
    67000,
    174000,
    60407,
    450000,
    180000,
    149612,
    69500,
    48500,
    70000,
    235500,
    48800,
    105000,
    48000,
    55000,
    95125,
    100000,
    90000,
    105000,
    72300,
    90000,
    100000,
    27000,
    480000,
    82000,
    92000,
    1967856,
    170200,
    42000,
    60000,
    283000,
    54120,
    65000,
    65000,
    165000,
    100000,
    180000,
    106000,
    47000,
    61000,
    150000,
    118000,
    300000,
    60240.96,
    99000,
    100625,
    40000,
    50000,
    149000,
    125000,
    150000,
    52000,
    190000,
    50000,
    140000,
    38000,
    280000,
    65000,
    73000,
    100000,
    240000,
    140000,
    124000,
    54000,
    35929,
    150000,
    41000,
    33000,
    84762,
    80000,
    17000,
    110000,
    49000,
    130000,
    52452,
    56000,
    45000,
    74000,
    90000,
    101500,
    145000,
    83000,
    151000,
    58000,
    350000,
    134000,
    123000,
    77000,
    120000,
    180000,
    120000,
    40000,
    350000,
    45000,
    80000,
    60000,
    85000,
    62246,
    80500,
    200000,
    57634,
    121700,
    150000,
    200000,
    60000,
    120000,
    50000,
    110000,
    78000,
    58000,
    280000,
    119000,
    58000,
    67000,
    65000,
    55,
    45000,
    230000,
    33000,
    100000,
    90000,
    36000,
    6300,
    200000,
    64000,
    77000,
    99000,
    85000,
    110000,
    124000,
    75,
    108000,
    107000,
    84000,
    50000,
    50000,
    168000,
    43000,
    52600,
    90000,
    57000,
    130000,
    76000,
    134000,
    185000,
    140000,
    56000,
    100000,
    48000,
    27500,
    166500,
    110000,
    180000,
    180000,
    110000,
    59000,
    223000,
    108000,
    60000,
    220000,
    100000,
    110000,
    124100,
    80000,
    103000,
    85,
    60000,
    61440,
    124387.2,
    90000,
    110000,
    105000,
    234000,
    60000,
    82000,
    84000,
    125000,
    90000,
    125000,
    125000,
    195000,
    40000,
    96385,
    122000,
    66214,
    70000,
    155000,
    96000,
    187,
    90000,
    5000,
    37500,
    35707,
    70000,
    42981.25,
    165000,
    99000,
    65000,
    280000,
    120000,
    150000,
    72000,
    150000,
    40440,
    180000,
    100000,
    110000,
    21.329,
    2302000,
    20000,
    180000,
    30000,
    100000,
    90,
    90000,
    242000,
    222000,
    73000,
    120000,
    56400,
    108000,
    43000,
    230000,
    93000,
    45000,
    121000,
    180000,
    125000,
    800000,
    50225.43,
    83000,
    83000,
    47000,
    405000,
    420000,
    30000,
    50000,
    51000,
    36000,
    52000,
    39300,
    40000,
    21800,
    39.3,
    124000,
    89000,
    140000,
    87000,
    30000,
    60722,
    96000,
    381000,
    85000,
    180000,
    137800,
    43,
    48000,
    90,
    43050,
    51100,
    85000,
    48000,
    363000,
    450000,
    100000,
    144000,
    79000,
    112000,
    260000,
    55000,
    480000,
    42000,
    85000,
    120000,
    45150,
    141882,
    52000,
    120000,
    120000,
    91200,
    182000,
    200000,
    303689,
    50000,
    130000,
    650000,
    41000,
    94000,
    85000,
    336000,
    145000,
    150000,
    42300,
    91700,
    93000,
    130000,
    99000,
    50000,
    182000,
    82000,
    52400,
    192000,
    172800,
    35000,
    370000,
    264000,
    120000,
    75000,
    60000,
    122000,
    180000,
    100000,
    55000,
    65000,
    45000,
    65000,
    65940,
    77000,
    55000,
    32500,
    130000,
    100000,
    134333,
    89000,
    132000,
    90000,
    99000,
    38356.2,
    66200,
    57000,
    130000,
    140000,
    265558.72,
    72007.42,
    34531,
    124000,
    170000,
    130000,
    160000,
    86068,
    158000,
    100000,
    53000,
    50000,
    110000,
    80000,
    72300,
    66000,
    185000,
    66000,
    36501.96,
    60325.01,
    75000,
    49800,
    57000,
    53000,
    50700,
    63855,
    20000,
    48000,
    120000,
    37000,
    220000,
    125000,
    25000,
    45000,
    110000,
    45000,
    75000,
    410000,
    2400000,
    135000,
    80,
    45000,
    90000,
    40000,
    74,
    320000,
    1300000,
    52000,
    75000,
    200000,
    100000,
    361000,
    65000,
    100000,
    140000,
    90000,
    165000,
    12000,
    120000,
    80000,
    47000,
    130500,
    1,
    150000,
    90000,
    200000,
    18000,
    36000,
    270000,
    72000,
    47000,
    78000,
    30000,
    89000,
    110000,
    180000,
    540000,
    86000,
    78000,
    110000,
    76000,
    65000,
    90000,
    140000,
    120000,
    117500,
    75510,
    240000,
    100000,
    100000,
    20000,
    180000,
    66667,
    800000,
    95000,
    70000,
    130000,
    53000,
    140000,
    40000,
    183831,
    79200,
    99000,
    100000,
    100000,
    70000,
    40000,
    515000,
    150000,
    120000,
    110000,
    65000,
    103,
    508000,
    163000,
    54000,
    170000,
    190000,
    220000,
    110000,
    1504,
    90000,
    89500,
    83000,
    74000,
    120000,
    161000,
    52186,
    92000,
    66000,
    126000.5,
    180000,
    85000,
    70000,
    141700,
    110000,
    93000,
    200000,
    290000,
    132630,
    180000,
    240000,
    203000,
    50000,
    93453,
    47385,
    229000,
    140000,
    150000,
    390000,
    350000,
    83500,
    90000,
    350000,
    192000,
    130000,
    115000,
    155000,
    170000,
    306000,
    100000,
    78000,
    65000,
    158000,
    130000,
    137000,
    720000,
    150000,
    100000,
    260000,
    150000,
    128000,
    100000,
    55000,
    69000,
    66000,
    170000,
    88000,
    130000,
    90000,
    99330,
    112800,
    68000,
    180000,
    115000,
    101000,
    145000,
    50000,
    144,
    190000,
    138000,
    248000,
    95300,
    180000,
    115000,
    92500,
    47200,
    90000,
    77000,
    170000,
    147200,
    58000,
    53000,
    165000,
    53000,
    140000,
    118337,
    77000,
    80000,
    160000,
    125000,
    125000,
    115000,
    140000,
    120000,
    60000,
    125000,
    60000,
    140000,
    93000,
    67000,
    16579500,
    38000,
    115000,
    440000,
    110000,
    60000,
    110000,
    130000,
    180000,
    130000,
    150000,
    108000,
    109000,
    130000,
    180000,
    47000,
    130000,
    105000,
    200000,
    160000,
    170000,
    118000,
    26000,
    80000,
    77000,
    2,
    100000,
    75000,
    11000,
    178000,
    55000,
    85000,
    93000,
    140000,
    170000,
    115000,
    112000,
    118000,
    79800,
    44000,
    110000,
    109000,
    140000,
    110800,
    110800,
    80000,
    140000,
    150000,
    75000,
    57000,
    134000,
    143000,
    104000,
    11000,
    135000,
    380000,
    101000,
    150000,
    98000,
    100000,
    112000,
    112000,
    120000,
    138000,
    65000,
    95000,
    128907,
    150000,
    68000,
    120000,
    185000,
    29450,
    101000,
    100000,
    60240.96,
    153800,
    140000,
    140000,
    128700,
    145000,
    50000,
    60000,
    792000,
    73000,
    84000,
    35000,
    111000,
    75000,
    79999,
    35000,
    200000,
    92000,
    152200,
    120000,
    146000,
    60840,
    51800,
    128490,
    70000,
    80000,
    90,
    99825,
    60000,
    88450,
    44.907,
    115200,
    35000,
    350000,
    61000,
    50657,
    3095,
    120000,
    20000,
    45000,
    149000,
    110000,
    159000,
    100000,
    60000,
    80000,
    95000,
    145000,
    67000,
    50000,
    137000,
    35000,
    58400,
    150000,
    78900,
    10000,
    150000,
    210000,
    416500,
    116000,
    300000,
    152300,
    230000,
    88060,
    81.783,
    6400,
    70000,
    235000,
    110000,
    48.359,
    75000,
    145000,
    30803,
    143000,
    144830,
    110000,
    90000,
    284000,
    40000,
    115000,
    77108,
    70000,
    42000,
    67765,
    126000,
    45000,
    30000,
    47291.36,
    92000,
    75,
    45000,
    85000,
    75000,
    70000,
    260000,
    129000,
    52,
    362000,
    243000,
    90000,
    87600,
    42000,
    40000,
    120000,
    72000,
    56000,
    250000,
    120000,
    1000000,
    68500,
    40000,
    160000,
    48000,
    85000,
    159000,
    80000,
    77000,
    105000,
    312100,
    155000,
    150000,
    76000,
    83000,
    41125,
    90000,
    14000,
    45045,
    74000,
    150000,
    114000,
    110000,
    300000,
    80000,
    145000,
    92914,
    60000,
    480000,
    100000,
    92914,
    76500,
    114897,
    43230,
    540000,
    124600,
    65000,
    41000,
    103800,
    100000,
    140000,
    100000,
    100000,
    244000,
    157729.26,
    50690,
    26000,
    50000,
    95000,
    167000,
    60000,
    60000,
    104000,
    156000,
    75903,
    250000,
    90000,
    162426,
    60000,
    139000,
    75000,
    90000,
    14000,
    90000,
    77406,
    240000,
    138000,
    150000,
    120000,
    39500,
    92000,
    100000,
    113000,
    54000,
    132.194,
    126000,
    118374,
    97476,
    95,
    90000,
    340000,
    151800.16,
    48000,
    63000,
    107784,
    92000,
    75000,
    32000,
    45000,
    250000,
    52800,
    155,
    108000,
    60000,
    35000,
    160000,
    46000,
    139000,
    80000,
    85000,
    124500,
    92000,
    253000,
    88500,
    58817.92,
    560000,
    20000,
    235000,
    136000,
    160000,
    690000,
    130000,
    85000,
    86000,
    570000,
    38000,
    100000,
    150000,
    46724,
    120000,
    127000,
    51500,
    70000,
    500000,
    48,
    86000,
    110000,
    165086,
    40000,
    40000,
    107.23,
    40000,
    420000,
    124500,
    70000,
    305000,
    80000,
    86000,
    69000,
    100000,
    107000,
    55000,
    136000,
    114500,
    61200,
    112000,
    130000,
    170000,
    120000,
    47710,
    450000,
    90000,
    185000,
    260000,
    115000,
    130000,
    500000,
    20000,
    25000,
    250000,
    104000,
    260000,
    100000,
    7000,
    237062,
    84000,
    130000,
    57000,
    61000,
    200000,
    50000,
    68000,
    15000,
    65000,
    150000,
    185000,
    150000,
    6000,
    150000,
    95000,
    180000,
    150000,
    170000,
    140000,
    69000,
    90000,
    154000,
    48,
    70000,
    123000,
    85000,
    141000,
    80000,
    155000,
    195000,
    175000,
    97200,
    119000,
    136500,
    407000,
    69365,
    255000,
    80000,
    88738,
    200000,
    200000,
    49000,
    390000,
    180000,
    170000,
    38000,
    54000,
    130000,
    140000,
    80500,
    130000,
    113000,
    145500,
    50000,
    92887,
    77000,
    235000,
    123000,
    100000,
    36000,
    62000,
    93000,
    75000,
    51700,
    85000,
    290000,
    50240,
    80000,
    2050000,
    65,
    150700,
    100000,
    195000,
    85000,
    80000,
    145000,
    142000,
    130000,
    400000,
    220000,
    90700,
    51000,
    85000,
    96000,
    96500,
    135000,
    80000,
    90000,
    130000,
    72900,
    83000,
    82000,
    130000,
    85000,
    96800,
    128000,
    180000,
    140000,
    77682,
    81500,
    100000,
    85000,
    43250,
    84000,
    104000,
    120000,
    83000,
    168000,
    64000,
    93000,
    145600,
    130000,
    120705,
    103000,
    270000,
    78292.77,
    78346,
    88000,
    87000,
    22000,
    35000,
    200000,
    120000,
    175000,
    269000,
    24000,
    111000,
    60000,
    50000,
    40000,
    160000,
    62643,
    72250,
    140000,
    135000,
    42000,
    147000,
    471408,
    100000,
    78000,
    47271,
    124700,
    60000,
    75000,
    94000,
    122000,
    135608,
    126000,
    73000,
    160000,
    175000,
    85000,
    40000,
    72000,
    126.225,
    70438,
    52500,
    92385,
    66000,
    51000,
    169000,
    49000,
    85000,
    145000,
    65000,
    143000,
    2180000,
    100000,
    72959,
    46000,
    89800,
    105000,
    85000,
    69382.17,
    75000,
    87000,
    38700,
    125000,
    61076,
    135495,
    77000,
    88500,
    89000,
    86000,
    37000,
    82000,
    300000,
    190000,
    96000,
    106217,
    125000,
    45000,
    68200,
    60000,
    74000,
    70000,
    90000,
    18000,
    68000,
    160000,
    185000,
    77000,
    265000,
    43000,
    147000,
    98000,
    120000,
    75000,
    125000,
    60240.96,
    115000,
    55000,
    660000,
    62000,
    38000,
    89000,
    76000,
    145000,
    100000,
    165000,
    60000,
    80000,
    67967.74,
    65000,
    135000,
    80000,
    120000,
    140000,
    185000,
    135000,
    133.57,
    200000,
    322000,
    45000,
    92000,
    75384,
    40000,
    63000,
    30000,
    22000,
    150000,
    48200,
    165000,
    120000,
    180000,
    135000,
    150000,
    22891,
    250000,
    120000,
    112000,
    250000,
    80300,
    38000,
    110000,
    100000,
    230000,
    96018,
    44000,
    75800,
    130,
    144495,
    76500,
    50000,
    39000,
    23000,
    135000,
    360000,
    110000,
    45000,
    65000,
    76,
    90000,
    77000,
    200000,
    80000,
    143000,
    160000,
    140000,
    80850,
    88000,
    81000,
    56000,
    74545,
    83500,
    30250,
    160000,
    134000,
    117000,
    150000,
    98000,
    120,
    280000,
    50,
    103000,
    185000,
    66714.38,
    90000,
    360000,
    420000,
    240000,
    41250,
    53000,
    45000,
    365000,
    125000,
    54000,
    72540,
    86487,
    200000,
    43257.4,
    85000,
    60029.62,
    75000,
    99800,
    110000,
    109000,
    110000,
    105000,
    69000,
    75000,
    119000,
    145000,
    48,
    97009,
    112000,
    72000,
    100000,
    260000,
    129489,
    213870,
    106000,
    80000,
    110000,
    72000,
    96000,
    105000,
    48000,
    110000,
    280000,
    70000,
    150000,
    135000,
    87000,
    485000,
    86000,
    155000,
    180000,
    45000,
    130000,
    24000,
    225000,
    108500,
    170000,
    30000,
    700000,
    550000,
    186000,
    140400,
    91000,
    87000,
    190000,
    40150,
    46000,
    127072,
    63000,
    99000,
    120000,
    130000,
    66000,
    270000,
    196000,
    210000,
    110000,
    151624,
    75000,
    105000,
    50,
    102000,
    230000,
    56000,
    270000,
    50000,
    195000,
    110000,
    230000,
    52300,
    140000,
    114000,
    66292.88,
    108000,
    115000,
    220000,
    144700,
    90000,
    140000,
    91683,
    90000,
    120000,
    103000,
    182219,
    90000,
    55000,
    47000,
    70000,
    240000,
    71000,
    90278,
    1,
    140000,
    45000,
    160000,
    39000,
    77000,
    165000,
    400000,
    100000,
    225867,
    125000,
    87000,
    110000,
    140000,
    57118,
    402500,
    108000,
    69000,
    157300,
    195200,
    110000,
    288000,
    219,
    100000,
    180000,
    129500,
    92000,
    160000,
    166100,
    15,
    170000,
    44000,
    110000,
    85000,
    240000,
    150000,
    119500,
    105000,
    42000,
    130000,
    85000,
    72000,
    247000,
    65000,
    95000,
    215000,
    67000,
    190000,
    300000,
    110000,
    135044,
    44500,
    100000,
    88000,
    400000,
    75000,
    120000,
    278000,
    74000,
    162421.88,
    170000,
    218000,
    140000,
    130000,
    50000,
    36000,
    99500,
    350000,
    180000,
    250000,
    96000,
    340000,
    39620,
    90000,
    88000,
    66390,
    73000,
    192000,
    85000,
    42000,
    125000,
    431000,
    62000,
    83500,
    133337,
    86000,
    280000,
    135000,
    100000,
    92000,
    140557,
    40000,
    53000,
    38569,
    80000,
    190000,
    40000,
    54126,
    70000,
    58600,
    107000,
    153660,
    33000,
    190000,
    126959,
    3000,
    35265.03,
    100000,
    180000,
    90000,
    320000,
    280,
    89000,
    300000,
    103000,
    200000,
    300000,
    76000,
    79000,
    48000,
    72000,
    50421,
    96000,
    130000,
    53000,
    150000,
    70000,
    130000,
    110000,
    75000,
    240000,
    100000,
    68000,
    182000,
    71000,
    65700,
    105000,
    160000,
    25000,
    107000,
    160000,
    160000,
    78000,
    130,
    110000,
    46000,
    250000,
    91000,
    212500,
    185400,
    142600,
    110500,
    85000,
    35000,
    114311,
    92000,
    100,
    65000,
    77000,
    246000,
    136000,
    133888,
    55000,
    115000,
    180000,
    147000,
    480000,
    400000,
    60000,
    137790,
    37830,
    72000,
    320817,
    110000,
    235000,
    144000,
    118000,
    44500,
    130000,
    50500,
    1300000,
    183000,
    211000,
    131000,
    73842,
    85000,
    45000,
    200000,
    89000,
    82000,
    35000,
    29500,
    60000,
    380000,
    130000,
    64800,
    85,
    185000,
    193000,
    81712,
    113000,
    200000,
    90000,
    116600,
    127000,
    82100,
    68000,
    148710.52,
    48000,
    62000,
    200000,
    38000,
    80000,
    128000,
    90000,
    134000,
    155000,
    150000,
    84500,
    35000,
    49140,
    79000,
    73500,
    470000,
    90000,
    63457,
    90000,
    70000,
    42000,
    150000,
    75000,
    158300,
    56000,
    55500,
    30000,
    230000,
    350000,
    44000,
    174000,
    120000,
    80000,
    119000,
    1111,
    95000,
    59600,
    170000,
    140000,
    50000,
    194000,
    70506,
    165000,
    80000,
    55443.72,
    85000,
    53880,
    67600,
    183000,
    176000,
    35000,
    70000,
    164000,
    60000,
    37550,
    16000,
    128000,
    60,
    67350,
    80000,
    95000,
    105000,
    140000,
    121400,
    80000,
    75000,
    95800,
    140000,
    30677.4,
    60004,
    62000,
    63000,
    50509,
    190000,
    140000,
    120000,
    55000,
    62000,
    50509,
    80000,
    38000,
    180000,
    205000,
    30000,
    140000,
    220000,
    160000,
    55000,
    180000,
    44000,
    160000,
    91800,
    137000,
    136000,
    115000,
    177000,
    180000,
    180000,
    45506,
    51000,
    88000,
    47000,
    160000,
    78313,
    137000,
    90000,
    206908.01,
    117000,
    52.5,
    600000,
    120000,
    123000,
    447000,
    198000,
    103000,
    75000,
    90000,
    88000,
    102000,
    60000,
    40000,
    170000,
    93000,
    121000,
    124000,
    50814,
    130000,
    130000,
    160000,
    130000,
    102278,
    34200,
    90000,
    180000,
    81700,
    79400,
    65000,
    150000,
    161000,
    56000,
    60000,
    450000,
    130000,
    19000,
    63342,
    160000,
    46371,
    90000,
    185000,
    205000,
    313751.46,
    56000,
    45000,
    65000,
    45000,
    42000,
    75000,
    666000,
    55000,
    129000,
    325000,
    90000,
    71000,
    177264,
    120000,
    392000,
    93000,
    66400,
    82.3,
    300000,
    37000,
    113000,
    90000,
    98300,
    73000,
    175000,
    200000,
    62000,
    210000,
    52000,
    124000,
    380000,
    134000,
    85000,
    360000,
    260,
    45000,
    60000,
    160000,
    360000,
    136000,
    90000,
    290000,
    210000,
    120000,
    525000,
    87000,
    120000,
    134000,
    475000,
    81000,
    36900,
    52084,
    100000,
    134000,
    123391,
    139500,
    111445,
    95000,
    98868,
    223000,
    190000,
    320000,
    93000,
    66000,
    90000,
    150000,
    120000,
    59937,
    85000,
    177000,
    519000,
    570000,
    400000,
    163000,
    23300,
    105000,
    146675.63,
    130000,
    800000,
    180000,
    50000,
    36000,
    102100,
    80000,
    60000,
    290000,
    85000,
    59103,
    160000,
    100000,
    180000,
    80,
    210000,
    46608,
    55000,
    94415,
    138446,
    140000,
    60000,
    39840,
    100000,
    54000,
    125000,
    700000,
    385000,
    79550,
    75500,
    120000,
    641690,
    690000,
    45000,
    136200,
    70000,
    150000,
    100000,
    140000,
    60000,
    132000,
    76000,
    115000,
    82320,
    111000,
    89000,
    114000,
    170000,
    59072,
    320000,
    45,
    70000,
    95000,
    246000,
    60000,
    61000,
    112000,
    670000,
    80000,
    77500,
    37000,
    191500,
    120500,
    150000,
    139216,
    115000,
    75000,
    211000,
    110000,
    99000,
    15000,
    65000,
    80000,
    11300,
    110000,
    108973.17,
    220000,
    314556,
    123000,
    61088,
    102409,
    148000,
    190000,
    48000,
    4000,
    57000,
    125000,
    600000,
    159000,
    288775,
    145.576,
    160000,
    39000,
    70000,
    70000,
    105000,
    180000,
    125843,
    215000,
    216000,
    91500,
    55000,
    32,
    55000,
    53000,
    178220.25,
    86000,
    160000,
    175000,
    55421,
    120000,
    700000,
    70000,
    120000,
    170000,
    62430,
    42000,
    110000,
    60000,
    952500,
    45180,
    100000,
    272000,
    35000,
    59829,
    129000,
    65000,
    155000,
    130000,
    300000,
    600000,
    62600,
    168000,
    152000,
    100000,
    121000,
    104000,
    70000,
    150000,
    68000,
    49850,
    110000,
    135000,
    200000,
    94000,
    71000,
    160000,
    55000,
    120000,
    180000,
    120000,
    92494,
    200000,
    90233,
    180,
    170500,
    206900,
    60000,
    154000,
    120000,
    700000,
    253768,
    91000,
    500000,
    80000,
    24000,
    79020,
    203000,
    193000,
    50000,
    80,
    380000,
    90000,
    150000,
    119000,
    106000,
    55000,
    75152,
    90000,
    70000,
    81000,
    77000,
    120000,
    230000,
    85000,
    41000,
    120000,
    116000,
    304680,
    59,
    95000,
    255200,
    243676,
    63856,
    70000,
    86000,
    108419,
    320000,
    60000,
    40000,
    240000,
    168000,
    119000,
    43000,
    60000,
    18000,
    140000,
    70461,
    120000,
    190000,
    100000,
    85000,
    210000,
    180335,
    163000,
    108000,
    132000,
    110000,
    2740,
    175000,
    40000,
    100000,
    350000,
    87639.89,
    124000,
    115000,
    54000,
    184000,
    113840,
    100000,
    67440,
    170000,
    101000,
    110000,
    83793,
    97917,
    148000,
    50000,
    36501,
    110000,
    250000,
    119000,
    332100,
    141000,
    600,
    205000,
    58000,
    13500,
    430000,
    160000,
    47080.72,
    200000,
    250000,
    300000,
    120,
    1200000,
    56000,
    103200,
    55000,
    197000,
    290000,
    121800,
    47,
    140000,
    86000,
    300000,
    210000,
    34537,
    200000,
    130000,
    104500,
    278835,
    78100,
    140000,
    44000,
    109000,
    100000,
    75000,
    48293,
    228139,
    68000,
    45000,
    364000,
    110000,
    72000,
    42000,
    58160,
    63251.06,
    74700,
    140500,
    72000,
    62000,
    130000,
    90000,
    125000,
    65000,
    94000,
    80000,
    91000,
    35000,
    186000,
    130000,
    65000,
    126700,
    59000,
    122000,
    56000,
    47080,
    95000,
    115000,
    110000,
    141000,
    95500,
    115000,
    244000,
    190000,
    140000,
    64600,
    180000,
    215000,
    1033000,
    350000,
    137073.78,
    100000,
    170000,
    500000,
    35000,
    52706,
    740000,
    64000,
    117335,
    64000,
    61000,
    45000,
    65000,
    33000,
    4452743,
    134000,
    48300,
    172000,
    100000,
    68000,
    118000,
    122000,
    78000,
    150000,
    125000,
    82133,
    102000,
    88300,
    132000,
    90000,
    110000,
    290000,
    173250,
    100000,
    169000,
    72000,
    70000,
    268400,
    228000,
    99000,
    350000,
    146000,
    92000,
    39870,
    67000,
    105000,
    26890,
    106000,
    53100,
    290000,
    90000,
    160000,
    80000,
    126000,
    307500,
    39000,
    72000,
    67200,
    63.204,
    60000,
    250000,
    94000,
    127000,
    90000,
    150000,
    154000,
    50000,
    70000,
    500000,
    105000,
    125000,
    150000,
    120000,
    150000,
    165630,
    260000,
    160000,
    42000,
    95000,
    192000,
    96000,
    255700,
    45000,
    121601,
    50000,
    45000,
    180000,
    10000,
    47000,
    80000,
    125000,
    180000,
    108400,
    150000,
    145000,
    83000,
    400000,
    140000,
    625000,
    155000,
    18073,
    175000,
    85154,
    99112,
    90000,
    90000,
    76800,
    140000,
    120000,
    71900,
    120000,
    144000,
    120000,
    90000,
    295000,
    209000,
    10000,
    166000,
    87450,
    134000,
    63000,
    300000,
    110000,
    170000,
    90000,
    88240,
    160000,
    55000,
    750000,
    124000,
    195000,
    150000,
    50000,
    74000,
    242550000,
    1,
    160000,
    90000,
    100000,
    90000,
    115000,
    175000,
    120000,
    115,
    90665,
    70000,
    120000,
    45000,
    95000,
    43000,
    116000,
    26500,
    175000,
    120000,
    210000,
    90000,
    120000,
    120000,
    90000,
    412500,
    90000,
    116000,
    105000,
    340000,
    74,
    62150,
    50000,
    65846,
    73900,
    170000,
    43760,
    67,
    162400,
    600000,
    85000,
    57500,
    45000,
    124687,
    52000,
    137000,
    160000,
    40000,
    56000,
    61600,
    75000,
    51000,
    92000,
    190000,
    37000,
    91000,
    132000,
    88,
    140000,
    100000,
    124000,
    74000,
    649,
    165000,
    60000,
    175000,
    150000,
    225000,
    81842.71,
    65000,
    560000,
    45000,
    1,
    48000,
    59000,
    43240,
    300000,
    82000,
    41025,
    30000000,
    38500,
    75,
    10000000,
    116170,
    70000,
    110000,
    167000,
    100000,
    52000,
    57330,
    97645,
    76072,
    80000,
    76000,
    100000,
    500000,
    80000,
    230000,
    110000,
    43130,
    210000,
    24,
    88000,
    133000,
    184000,
    281600,
    80000,
    66292.88,
    40.8,
    170000,
    95000,
    88000,
    158000,
    57500,
    95300,
    540000,
    50000,
    240000,
    130000,
    210000,
    98000,
    150000,
    45000,
    192000,
    425000,
    150000,
    49000,
    41000,
    103488,
    105000,
    55000,
    200000,
    200000,
    280000,
    57200,
    72000,
    82051,
    32000,
    53899.67,
    130000,
    160000,
    220000,
    45000,
    180000,
    28000,
    35400,
    150000,
    320000,
    110000,
    215000,
    25000,
    164000,
    55000,
    96870,
    91300,
    130000,
    225000,
    99584,
    45000,
    87000,
    116795,
    72000,
    36.6,
    115000,
    500000,
    190000,
    60000,
    75000,
    88414,
    660000,
    52200,
    200000,
    250000,
    89000,
    114897,
    330000,
    66,
    140000,
    58700,
    100000,
    160000,
    80914.8,
    65000,
    226000,
    320000,
    73200,
    610,
    154000,
    55000,
    400000,
    67000,
    7800000,
    151000,
    25000,
    135000,
    148000,
    100000,
    42500,
    95000,
    315000,
    41000,
    145000,
    345000,
    200000,
    43000,
    170,
    116000,
    115000,
    69000,
    98000,
    102000,
    190000,
    120000,
    60000,
    340000,
    50000,
    118000,
    62500,
    292000,
    54000,
    130000,
    80000,
    177000,
    80300,
    112000,
    53800,
    2500000,
    190000,
    280,
    128000,
    500000,
    108000,
    55000,
    135000,
    172600,
    100000,
    68600,
    172600,
    89000,
    52000,
    150000,
    120000,
    65000,
    313000,
    91000,
    210000,
    53500,
    112,
    300000,
    164000,
    17000,
    48803,
    38000,
    80000,
    186000,
    94000,
    500000,
    484000,
    52,
    55000,
    42000,
    158000,
    150000,
    125000,
    80000,
    125000,
    96000,
    32000,
    89000,
    165000,
    111000,
    76000,
    120000,
    126800,
    74000,
    100000,
    35000,
    190000,
    105000,
    150540,
    23,
    109000,
    75000,
    90000,
    230000,
    125000,
    105000,
    250000,
    270000,
    170000,
    178000,
    289414,
    179000,
    66000,
    30000,
    73.986,
    190000,
    95000,
    39000,
    160000,
    115,
    93500,
    58216.87,
    175000,
    184000,
    50000,
    138000,
    182000,
    260000,
    53000,
    277716,
    177000,
    37500,
    172600,
    107000,
    145000,
    105000,
    110000,
    350000,
    166000,
    37000,
    40000,
    150000,
    105000,
    137000,
    125000,
    85376,
    970,
    85000,
    35000,
    65127,
    145000,
    108,
    110000,
    105000,
    150000,
    100000,
    48000,
    125700,
    70000,
    48789,
    38700,
    86785,
    194000,
    86000,
    52000,
    60000,
    305300,
    190000,
    53000,
    290000,
    85000,
    265000,
    290000,
    2700000,
    243516,
    160000,
    63000,
    67700,
    8800,
    47175,
    35000,
    316075,
    48000,
    68000,
    110000,
    53000,
    198000,
    65000,
    130000,
    62000,
    120000,
    84590,
    50000,
    165000,
    58000,
    3500000,
    350000,
    105000,
    56,
    1031250,
    54167.33,
    195000,
    61440.32,
    63000,
    120000,
    232000,
    100000,
    159000,
    45000,
    80000,
    300541,
    870000,
    273208,
    350000,
    37.8,
    85000,
    100000,
    38252,
    40000,
    69000,
    100000,
    42000,
    80000,
    23855,
    325000,
    41000,
    60000,
    77000,
    11000,
    138000,
    90000,
    90000,
    140690,
    90000,
    140251,
    50000,
    200000,
    17000,
    100,
    384150,
    28000,
    78000,
    70000,
    36205,
    146000,
    35000,
    75000,
    58220,
    145000,
    36205,
    130000,
    280000,
    750000,
    119623.84,
    67000,
    133000,
    70000,
    89920,
    60000,
    66500,
    115000,
    40000,
    70000,
    135000,
    120,
    45000,
    81000,
    58000,
    49000,
    123000,
    335000,
    82612,
    45000,
    133000,
    1377600,
    160000,
    60000,
    78359,
    90000,
    110000,
    76000,
    100000,
    134000,
    62000,
    155364,
    310000,
    224000,
    115000,
    40000,
    13000,
    68000,
    76428,
    68000,
    90000,
    34000,
    48000,
    57525,
    280000,
    126767,
    130000,
    150000,
    400000,
    85000,
    105000,
    73000,
    110000,
    190000,
    40000,
    70000,
    56000,
    103000,
    60600,
    280000,
    96000,
    82000,
    115000,
    34000,
    500000,
    150000,
    43000,
    51000,
    104561,
    200000,
    130000,
    62900,
    240000,
    250000,
    73.14,
    70000,
    140000,
    109767,
    111242.73,
    100377,
    69000,
    84400,
    231800,
    102500,
    62000,
    30000,
    91767,
    86000,
    55000,
    85000,
    63000,
    38000,
    65000,
    180000,
    138000,
    95000,
    47958.75,
    73600,
    4300,
    120000,
    210000,
    100000,
    126000,
    180000,
    119000,
    110000,
    65000,
    112000,
    77000,
    12000,
    169000,
    66500,
    209000,
    147000,
    210000,
    100000,
    63500,
    158397.5,
    200000,
    172000,
    25000,
    120000,
    120000,
    160000,
    104000,
    110000,
    54000,
    79600,
    368300,
    56000,
    107000,
    149802,
    65000,
    64500,
    90700,
    195000,
    58000,
    136250,
    107520,
    104000,
    127000,
    60000,
    57000,
    120000,
    90000,
    95100,
    125000,
    22000,
    48000,
    850000,
    360000,
    160000,
    70000,
    55000,
    200,
    133758,
    140000,
    75000,
    96000,
    80000,
    134000,
    80,
    90000,
    204000,
    120000,
    59890,
    35900,
    91000,
    4500000,
    212000,
    52000,
    120000,
    130000,
    89000,
    270000,
    64000,
    78678,
    60000,
    315000,
    170000,
    115000,
    143000,
    180000,
    250000,
    93000,
    66390,
    116000,
    99143,
    67000,
    54000,
    123000,
    110100,
    64000,
    22500,
    135450,
    81600,
    100000,
    64649,
    80000,
    500000,
    96000,
    56000,
    92000,
    5000,
    60000,
    98000,
    64000,
    300000,
    90000,
    66000,
    76800,
    65930,
    32500,
    25000,
    110000,
    160000,
    95000,
    240000,
    1490000,
    43,
    440000,
    215000,
    60000,
    80000,
    103000,
    70000,
    120000,
    120000,
    70000,
    107902,
    42000,
    73315,
    200000,
    100000,
    49000,
    177000,
    42000,
    640000,
    55000,
    95000,
    140000,
    23800,
    100000,
    250000,
    64100,
    130000,
    38000,
    113000,
    40000,
    105300,
    59000,
    95000,
    75000,
    307000,
    80000,
    180000,
    84200,
    350000,
    45000,
    1,
    155000,
    130000,
    150000,
    98000,
    50000,
    80000,
    160000,
    240000,
    73000,
    64505,
    190000,
    111500,
    120000,
    88000,
    190000,
    102370,
    142400,
    155000,
    135000,
    135000,
    77000,
    38000,
    168000,
    22100,
    100000,
    260000,
    78000,
    85000,
    170000,
    1680000,
    320000,
    50000,
    42000,
    51080,
    38900,
    140000,
    63000,
    364000,
    165000,
    27000,
    85000,
    450000,
    66777,
    68000,
    91753.4,
    89000,
    64000,
    100650,
    70000,
    36000,
    91000,
    50000,
    157834,
    119684,
    262000,
    60000,
    70000,
    132000,
    225000,
    63000,
    130000,
    150000,
    180000,
    95000,
    165000,
    220000,
    400000,
    64144,
    98500,
    95000,
    270000,
    70000,
    43775,
    210000,
    508252,
    50000,
    49.623,
    110000,
    400000,
    140000,
    139000,
    117900,
    200000,
    200000,
    40000,
    95000,
    130000,
    160000,
    124500,
    37500,
    150000,
    180000,
    150000,
    110000,
    55900,
    46000,
    93000,
    75000,
    65000,
    90000,
    67.25,
    49514,
    130,
    92000,
    72000,
    97000,
    110000,
    60000,
    160000,
    198000,
    35000,
    95000,
    800000,
    37000,
    87000,
    142000,
    38000,
    200000,
    75000,
    120000,
    340000,
    90000,
    230000,
    200000,
    150000,
    500000,
    17365,
    108000,
    91000,
    13000,
    42000,
    86000,
    3000000,
    110000,
    120000,
    41000,
    173300,
    240000,
    150000,
    103000,
    83392,
    5000,
    69889,
    135000,
    2500,
    103,
    100000,
    130000,
    176000,
    73000,
    80000,
    220000,
    88000,
    45000,
    38500,
    94000,
    145000,
    512500,
    125000,
    65000,
    40000,
    67285,
    78000,
    36000,
    183000,
    110000,
    62834,
    60,
    79000,
    160.5,
    92950,
    200000,
    25000,
    72000,
    48000,
    174400,
    56000,
    1750000,
    68500,
    95000,
    150000,
    80000,
    145000,
    141000,
    104000,
    35000,
    55000,
    50000,
    160000,
    190000,
    80000,
    66000,
    160000,
    56209,
    122000,
    52000,
    100,
    65292,
    63500,
    120000,
    104000,
    81000,
    67000,
    37000,
    150000,
    85000,
    47000,
    200000,
    189000,
    16000,
    130000,
    90000,
    48000,
    45000,
    200000,
    120000,
    125000,
    150000,
    125000,
    500000,
    64000,
    74300,
    46000,
    72000,
    455000,
    164000,
    55600,
    120000,
    455000,
    167000,
    57000,
    90000,
    106050,
    160000,
    120000,
    143000,
    90000,
    144000,
    158000,
    30000,
    74000,
    44000,
    116000,
    160000,
    150000,
    187980,
    165000,
    125000,
    120000,
    70000,
    34000,
    140000,
    33400,
    75000,
    40000,
    66000,
    42000,
    151150,
    90000,
    200000,
    108700,
    90000,
    60000,
    78200,
    280000,
    97500,
    194000,
    250000,
    36000,
    165000,
    65000,
    77352,
    145000,
    65000,
    8000,
    175000,
    290000,
    99000,
    51000,
    41600,
    80000,
    70000,
    50000,
    400000,
    66200,
    28000,
    200000,
    60000,
    80000,
    205000,
    120000,
    180000,
    100000,
    53000,
    275000,
    20000,
    250000,
    336000,
    152000,
    44000,
    105000,
    52000,
    120000,
    105000,
    58300,
    418000,
    70258,
    46000,
    189000,
    30000,
    50000,
    193000,
    141534,
    250000,
    50662,
    162000,
    76000,
    130000,
    51200,
    35000,
    93000,
    65000,
    36400,
    62000,
    89924,
    32209,
    250000,
    70000,
    78000,
    250000,
    150000,
    141600,
    58000,
    105000,
    73000,
    140000,
    95000,
    87000,
    82000,
    93000,
    125000,
    33925,
    100000,
    160800,
    67000,
    160000,
    44000,
    286000,
    110000,
    170000,
    44972,
    42000,
    49397.59,
    306000,
    75000,
    60000,
    116000,
    56250,
    55,
    279000,
    60000,
    437500,
    120000,
    170000,
    145000,
    3500000,
    900000,
    138000,
    52000,
    38500,
    117000,
    140438,
    176000,
    80000,
    100000,
    100000,
    14000,
    150000,
    102850,
    50000,
    125000,
    103000,
    205000,
    50100,
    90000,
    116000,
    151999,
    300000,
    115000,
    98000,
    80000,
    118500,
    205000,
    750000,
    115000,
    156000,
    280000,
    200000,
    115000,
    160000,
    120000,
    150000,
    550000,
    48400,
    70000,
    100024,
    114000,
    120000,
    42123,
    500000,
    55341.56,
    120000,
    45000,
    103800,
    20000,
    248000,
    30000,
    200000,
    72000,
    70000,
    44000,
    55000,
    74000,
    77,
    63000,
    51000,
    32.941,
    53000,
    200000,
    42000,
    80000,
    95000,
    55000,
    115000,
    110000,
    100000,
    125000,
    115000,
    69000,
    102000,
    69700,
    73000,
    130000,
    440000,
    87800,
    77800,
    130000,
    30000,
    102680,
    65000,
    25000,
    50000,
    70000,
    60000,
    1,
    135000,
    74000,
    80000,
    90000,
    46000,
    135000,
    100000,
    69000,
    130000,
    100000,
    650000,
    15000,
    64000,
    100000,
    120000,
    180000,
    96000,
    252000,
    170000,
    550000,
    80000,
    38700,
    38700,
    26000,
    100445,
    1,
    250000,
    37500,
    100000,
    90361,
    50000,
    140000,
    197680,
    56000,
    115000,
    100000,
    130000,
    80000,
    60000,
    50000,
    73923,
    52600,
    41500,
    50000,
    112800,
    50512,
    125000,
    680000,
    680000,
    145121,
    46030.06,
    100000,
    123000,
    140000,
    1439100,
    200000,
    202346.08,
    95000,
    82000,
    88000,
    98280,
    28000000,
    185000,
    120000,
    60000,
    48331,
    100000,
    41,
    70041.54,
    70000,
    61312,
    210000,
    100000,
    82200,
    123000,
    40000,
    102000,
    195000,
    72600,
    250000,
    75000,
    50000,
    195000,
    130000,
    90000,
    250000,
    38000,
    58000,
    54000,
    180000,
    144000,
    65000,
    80000,
    103000,
    25000,
    77000,
    125000,
    101000,
    100000,
    180000,
    60000,
    78000,
    70000,
    50000,
    75000,
    110000,
    129000,
    190000,
    82100,
    180000,
    900000,
    145000,
    85000,
    37000,
    44150,
    70000,
    80000,
    65000,
    140000,
    250000,
    480000,
    78811,
    51500,
    70000,
    110000,
    25000,
    38000,
    125000,
    5500000,
    65000,
    8500,
    206039,
    129000,
    31000,
    33000,
    140000,
    95000,
    90000,
    190000,
    85000,
    70000,
    120000,
    40000,
    69007.14,
    105000,
    180266,
    67000,
    70000,
    148,
    50000,
    61280,
    112000,
    20000,
    200000,
    106000,
    40000,
    97000,
    60000,
    90000,
    82000,
    56000,
    200000,
    160000,
    85000,
    120000,
    102500,
    216220,
    145000,
    144000,
    106478,
    140000,
    191000,
    228000,
    280000,
    201000,
    140000,
    176131,
    110000,
    156000,
    170000,
    66090,
    114000,
    36000,
    100000,
    173340,
    76000,
    179000,
    89000,
    92000,
    85600,
    139150,
    175000,
    122000,
    111111,
    117000,
    86500,
    85000,
    85000,
    125100,
    135000,
    104630.98,
    100000,
    175000,
    138000,
    103000,
    130,
    160000,
    120000,
    176000,
    160000,
    145000,
    105000,
    109000,
    100700,
    73000,
    92000,
    175000,
    109,
    94377,
    115000,
    120000,
    125000,
    160000,
    145000,
    202773,
    95000,
    120000,
    265000,
    136000,
    183000,
    180000,
    98800,
    89000,
    190000,
    91200,
    170000,
    30000,
    147000,
    80000,
    62000,
    140000,
    350000,
    109000,
    39175.51,
    31000,
    101000,
    130000,
    125000,
    150000,
    56000,
    138000,
    100,
    113000,
    98800,
    173754,
    140000,
    160000,
    100000,
    170000,
    125000,
    300000,
    60000,
    120000,
    450,
    9500,
    110,
    135000,
    195000,
    130000,
    100000,
    78000,
    95000,
    98280,
    120000,
    97000,
    85000,
    94320,
    158000,
    110000,
    110000,
    96000,
    150000,
    150000,
    90000,
    90,
    150000,
    40000,
    40000,
    100000,
    1200000,
    183000,
    175000,
    90000,
    82000,
    165000,
    210000,
    140,
    150000,
    50000,
    120000,
    180000,
    92000,
    21100,
    400000,
    60000,
    129556.98,
    130000,
    110000,
    50,
    214000,
    46000,
    69800,
    85000,
    210000,
    158000,
    135000,
    230000,
    60000,
    60000,
    10300,
    72220,
    172000,
    185000,
    40000,
    139500,
    52000,
    42000,
    106000,
    61000,
    400,
    114000,
    67500,
    55000,
    95000,
    45816,
    90000,
    163000,
    1367.46,
    56000,
    63855,
    45000,
    312000,
    585000,
    210000,
    129000,
    180000,
    153800,
    174000,
    206890,
    86000,
    185000,
    82800,
    87750,
    79000,
    142184,
    110000,
    170000,
    50000,
    106000,
    53000,
    156630,
    160000,
    100000,
    204400,
    50000,
    78000,
    100000,
    190000,
    110000,
    81500,
    180000,
    3750000,
    68000,
    60000,
    50000,
    124476,
    60000,
    130000,
    67000,
    96000,
    68000,
    150000,
    90,
    77370,
    33000,
    60000,
    155938,
    180765,
    184810.42,
    70000,
    180000,
    51000,
    55000,
    180000,
    140000,
    100000,
    120,
    112922,
    37000,
    60902,
    10000,
    40000,
    80000,
    80000,
    65000,
    36000,
    89700,
    230000,
    130000,
    145000,
    82000,
    52000,
    150000,
    120000,
    104000,
    113000,
    300000000,
    62000,
    160000,
    250000,
    90000,
    68500,
    100000,
    115000,
    112000,
    44000,
    108220,
    237000,
    82700,
    69000,
    85000,
    210000,
    86200,
    180600,
    140000,
    100000,
    220000,
    125000,
    149000,
    60000,
    93000,
    90000,
    200000,
    92800,
    120000,
    60000,
    74000,
    55000,
    240000,
    94000,
    89085,
    65000,
    72000,
    138000,
    85000,
    115000,
    105000,
    165000,
    45000,
    85000,
    192000,
    150000,
    110000,
    160000,
    105000,
    70000,
    65000,
    220000,
    90000,
    240000,
    47000,
    120000,
    85000,
    150000,
    44000,
    176000,
    350000,
    97000,
    300000,
    171000,
    890000,
    4300,
    81000,
    60000,
    305000,
    110000,
    120000,
    90000,
    166000,
    138000,
    47000,
    160000,
    115000,
    180000,
    38000,
    101000,
    65000,
    455000,
    68000,
    90000,
    150000,
    685,
    87000,
    125000,
    138000,
    110000,
    40000,
    85000,
    2000000,
    300000,
    68300,
    193000,
    73528,
    150000,
    128000,
    80000,
    53785,
    60000,
    50625,
    185000,
    46000,
    160000,
    105000,
    75000,
    105324,
    160000,
    190000,
    115000,
    1300,
    48000,
    90000,
    45000,
    111000,
    1800,
    40300,
    85500,
    173518,
    16000,
    95000,
    284000,
    127000,
    85000,
    56000,
    64000,
    297000,
    170000,
    56000,
    130000,
    70000,
    150000,
    57000,
    98000,
    200360,
    130000,
    41000,
    76769,
    45000,
    64500,
    100000,
    141500,
    60000,
    120000,
    60000,
    140000,
    140000,
    110000,
    140000,
    45000,
    90000,
    102000,
    160000,
    200000,
    94000,
    44000,
    95,
    75156,
    18000,
    95000,
    50000,
    224000,
    1000000,
    44800,
    105000,
    155500,
    110000,
    166000,
    2,
    60000,
    91800,
    500000,
    33498,
    105000,
    65000,
    1000000,
    30000,
    110000,
    155000,
    160000,
    135000,
    120000,
    138750,
    110000,
    55000,
    132000,
    112975,
    100000,
    90000,
    77000,
    88900,
    60000,
    85000,
    94000,
    60000,
    78000,
    106000,
    74000,
    180000,
    65000,
    36500,
    126299,
    101000,
    89000,
    40000,
    3800000,
    50000,
    138000,
    150000,
    120000,
    183000,
    42000,
    8000,
    85000,
    40000,
    109000,
    54000,
    177000,
    137000,
    100000,
    171000,
    105000,
    120000,
    125000,
    370000,
    96000,
    230000,
    80000,
    62000,
    65000,
    130000,
    120000,
    129000,
    75000,
    80000,
    85516,
    41280,
    125000,
    60000,
    25000,
    180000,
    73000,
    2000,
    122000,
    196122,
    200000,
    8800000,
    140000,
    150000,
    48800,
    100000,
    170000,
    160000,
    180000,
    85000,
    65000,
    29000,
    185000,
    148000,
    59000,
    210000,
    114000,
    135000,
    30000,
    45000,
    45000,
    45000,
    84550,
    220000,
    163000,
    125000,
    71000,
    200000,
    38000,
    84000,
    45000,
    73425,
    144000,
    90000,
    180000,
    215000,
    88000,
    90000,
    92887,
    80000,
    37,
    123000,
    870000,
    200000,
    125000,
    72000,
    150000,
    140000,
    210000,
    72000,
    52183,
    261000,
    135000,
    73000,
    45243,
    90665,
    100000,
    92500,
    224000,
    133758,
    45000,
    215000,
    92000,
    123000,
    100000,
    60000,
    112600,
    175000,
    26000,
    120000,
    95000,
    600000,
    103000,
    103,
    96500,
    105000,
    42000,
    500000,
    215000,
    165000,
    49500,
    12000,
    562452,
    228000,
    40000,
    100000,
    150000,
    69000,
    70500,
    40500,
    75000,
    40000,
    148000,
    160000,
    44000,
    114000,
    90000,
    154000,
    40000,
    133000,
    128800,
    120000,
    259000,
    55000,
    121000,
    133000,
    90000,
    100000,
    60027,
    33000,
    7000,
    140000,
    103000,
    180000,
    50100,
    48000,
    50000,
    197500,
    140000,
    100039,
    86000,
    100000,
    70000,
    145000,
    115000,
    72000,
    57599,
    80,
    210000,
    89000,
    89900,
    94000,
    115000,
    150,
    72000,
    105000,
    70000,
    180000,
    41000,
    42000,
    95000,
    50000,
    58002,
    48000,
    630000,
    338000,
    99676,
    153000,
    42000,
    80000,
    125000,
    85000,
    115342,
    45000,
    125000,
    90850,
    160000,
    71000,
    101157,
    98412,
    44000,
    250000,
    65705,
    169000,
    51000,
    320000,
    158000,
    20000,
    280000,
    280000,
    260000,
    201400,
    99900,
    120000,
    190000,
    125000,
    400000,
    57000,
    120000,
    90000,
    80000,
    140000,
    100000,
    164500,
    107000,
    121700,
    64000,
    78000,
    245000,
    112000,
    346000,
    15000,
    115000,
    192220,
    104000,
    96000,
    115000,
    81500,
    230000,
    105000,
    89300,
    340000,
    160000,
    340000,
    272000,
    60000,
    4200000,
    65000,
    91900,
    140000,
    130000,
    140000,
    58000,
    125000,
    100000,
    100000,
    115000,
    117000,
    20000,
    58000,
    56000,
    64000,
    25000,
    80000,
    49127,
    68000,
    70000,
    53000,
    140,
    140000,
    100000,
    100000,
    60000,
    60000,
    508600,
    270000,
    15900,
    182000,
    65000,
    67210.4,
    87500,
    400000,
    100000,
    305000,
    400000,
    35000,
    315000,
    88000,
    190000,
    102000,
    100000,
    34000,
    170000,
    107000,
    90000,
    80000,
    65000,
    130000,
    250000,
    110000,
    650000,
    500000,
    74500,
    75000,
    250000,
    75000,
    81870,
    320000,
    95100,
    78000,
    170000,
    184000,
    17000,
    95000,
    160000,
    33000,
    45000,
    160000,
    600000,
    85000,
    115000,
    145000,
    88000,
    77173,
    130166,
    310000,
    540,
    147675.61,
    185000,
    95000,
    400500,
    105000,
    102000,
    80000,
    280000,
    135000,
    220000,
    150000,
    61500,
    104000,
    123,
    174084,
    60000,
    85000,
    89000,
    239412,
    110250,
    105000,
    60000,
    140000,
    100000,
    190500,
    163295,
    107000,
    331000,
    116000,
    240000,
    44000,
    131042,
    75000,
    130000,
    32500,
    77589.96,
    130000,
    128250,
    179630,
    1250000,
    136000,
    200000,
    111680,
    136509,
    45355,
    119000,
    130000,
    32000,
    350000,
    110000,
    36000,
    75903,
    65333,
    148529.67,
    165000,
    46000,
    114000,
    130000,
    120000,
    88000,
    100000,
    73000,
    276000,
    117000,
    140000,
    180000,
    4500000,
    330000,
    90000,
    77954.58,
    140000,
    94000,
    500000,
    206000,
    61000,
    200000,
    38000,
    237000,
    189000,
    166000,
    54216,
    50000,
    50000,
    49000,
    60000,
    102300,
    52000,
    85700,
    90023,
    42000,
    63000,
    110000,
    60200,
    69000,
    183698,
    63000,
    132800,
    75000,
    63000,
    160000,
    90000,
    190000,
    125000,
    450000,
    75000,
    76000,
    71000,
    440000,
    187797,
    200000,
    53143,
    89000,
    62000,
    90500,
    75,
    64000,
    72000,
    14500,
    156615,
    154000,
    216000,
    20000,
    850000,
    77000,
    45000,
    120000,
    60000,
    90000,
    200000,
    64,
    93000,
    201000,
    105000,
    220000,
    130000,
    125334,
    1040000,
    115000,
    65000,
    609000,
    145000,
    100000,
    140000,
    230000,
    155000,
    89350,
    90000,
    42000,
    60000,
    71000,
    45000,
    116400,
    240000,
    90000,
    135000,
    132000,
    92300,
    48000,
    115000,
    60000,
    69000,
    43000,
    210000,
    60240.96,
    100000,
    250000,
    150000,
    68000,
    200000,
    60000,
    95000,
    1420000,
    78000,
    18,
    119220,
    66265,
    75000,
    5400,
    200000,
    69000,
    62000,
    26000,
    94879,
    430000,
    128000,
    178000,
    175000,
    120000,
    240000,
    29037,
    59000,
    123000,
    161699,
    140000,
    207,
    100000,
    290000,
    70000,
    86987.95,
    140000,
    50000,
    227000,
    89000,
    39000,
    40000,
    110000,
    83400,
    170,
    149800,
    95000,
    59680,
    90000,
    290000,
    130000,
    79922.48,
    107000,
    390000,
    141,
    85500,
    160000,
    120000,
    750000,
    79000,
    150000,
    140000,
    120000,
    96000,
    52000,
    135,
    73000,
    345000,
    78000,
    50000,
    95600,
    167.758,
    70000,
    400000,
    140000,
    305000,
    170000,
    75000,
    155000,
    71068,
    315000,
    47866,
    105000,
    120000,
    82500,
    105000,
    81800,
    190000,
    52800,
    102000,
    100000,
    4879000,
    120000,
    66000,
    135000,
    500000,
    110000,
    105000,
    196000,
    77000,
    300000,
    300000,
    200000,
    230000,
    173000,
    56600,
    99000,
    2141000,
    90000,
    130000,
    14000,
    61000,
    121000,
    260000,
    2080000,
    57000,
    73000,
    78000,
    113000,
    202000,
    125000,
    200000,
    115000,
    55000,
    43930,
    168500,
    324000,
    190000,
    160000,
    27000,
    53.699,
    65000,
    60000,
    103000,
    187000,
    175000,
    150000,
    91009,
    60000,
    60000,
    119200,
    179630,
    84000,
    39000,
    35000,
    117420,
    125000,
    140000,
    507571,
    310000,
    3500,
    108000,
    65225,
    140000,
    42900,
    51700,
    67000,
    87000,
    170000,
    200000,
    290000,
    42000,
    37200,
    49700,
    75000,
    116.586,
    38500,
    342500,
    140000,
    250000,
    196600,
    118000,
    42180,
    145000,
    99800,
    147500,
    300000,
    132000,
    120000,
    103000,
    54000,
    93000,
    250000,
    143000,
    170000,
    73770,
    90000,
    75000,
    340000,
    93000,
    240000,
    64600,
    220000,
    1800,
    140000,
    53000,
    180000,
    144000,
    68000,
    200000,
    125000,
    40000,
    40233,
    160000,
    120000,
    190000,
    100000,
    58540.88,
    260000,
    94000,
    54800,
    120000,
    72000,
    159000,
    143000,
    79200,
    91542,
    400000,
    89548.2,
    64000,
    139000,
    210000,
    88000,
    73000,
    167000,
    1550000,
    90800,
    140000,
    50000,
    164263,
    66000,
    130000,
    281250,
    130000,
    140000,
    975000,
    65000,
    150000,
    64900,
    40000,
    448000,
    270000,
    30000,
    36000,
    180000,
    90000,
    95000,
    400000,
    130000,
    85000,
    110000,
    66453,
    380000,
    401000,
    88000,
    110000,
    45000,
    370000,
    210,
    3000999,
    67230,
    69482,
    100000,
    95000,
    65000,
    29300,
    51000,
    62000,
    40000,
    90000,
    190000,
    48900,
    123105,
    74000,
    34000,
    105000,
    98000,
    145000,
    179630,
    112698.99,
    140000,
    200000,
    223000,
    24099.9,
    78000,
    55000,
    67000,
    200000,
    100000,
    315000,
    48700,
    73000,
    140000,
    105000,
    90200,
    238400,
    72000,
    30000,
    293995,
    91400,
    39000,
    46867.47,
    52000,
    47000,
    129395,
    128000,
    46000,
    50600,
    90000,
    145000,
    73000,
    115000,
    25000,
    80000,
    115000,
    350000,
    250000,
    13800,
    246000,
    250000,
    100000,
    8000000,
    78000,
    125400,
    48686,
    460000,
    95000,
    80000,
    110000,
    133000,
    67814,
    30000,
    165000,
    65000,
    61000,
    180000,
    280000,
    90000,
    220000,
    120000,
    130000,
    66000,
    72480,
    299902,
    70000,
    45000,
    81000,
    110000,
    99000,
    90000,
    73600,
    28600,
    60000,
    30000,
    140000,
    35009,
    88481.7,
    105000,
    180000,
    280000,
    50000,
    67000,
    170000,
    165000,
    94000,
    320000,
    86000,
    120000,
    135000,
    94000,
    95000,
    58000,
    360000,
    54.7,
    40000,
    72000,
    77000,
    44000,
    170000,
    80000,
    20000,
    52000,
    110000,
    52500,
    77500,
    86000,
    15,
    49000,
    140000,
    190500,
    105750,
    70000,
    92000,
    90000,
    180000,
    100000,
    572000,
    122000,
    60000,
    110000,
    89630,
    48000,
    72500,
    130000,
    156000,
    120000,
    22500,
    134000,
    150000,
    93000,
    93000,
    50400,
    95000,
    120000,
    68000,
    180000,
    76000,
    229714,
    97000,
    28000,
    65000,
    156014,
    135000,
    192280,
    115000,
    130000,
    158000,
    66000,
    450000,
    38433,
    104812,
    200000,
    300000,
    100000,
    180000,
    88000,
    89620,
    220000,
    40000,
    220000,
    42367,
    101000,
    146700,
    170000,
    100000,
    40000,
    55000,
    6800,
    35000,
    135000,
    58000,
    62627,
    14890,
    115000,
    72000,
    73000,
    22000,
    103000,
    6093,
    121000,
    15000,
    49000,
    9000,
    21000,
    47000,
    47048,
    21000,
    61590,
    30000,
    75000,
    36500,
    130000,
    34000,
    45750,
    7000,
    65000,
    42000,
    80000,
    45000,
    118000,
    100000,
    57000,
    32000,
    53000,
    74000,
    45000,
    180000,
    42000,
    120000,
    75000,
    120000,
    35400,
    108000,
    88800,
    46000,
    150000,
    8700,
    35000,
    36000,
    40000,
    30000,
    25000,
    85000,
    98000,
    128697,
    54000,
    90000,
    150000,
    80000,
    1600,
    88000,
    930,
    150000,
    70000,
    110000,
    15000,
    230000,
    908000,
    117000,
    35000,
    35000,
    34000,
    80000,
    50000,
    130000,
    57000,
    41500,
    21000,
    85000,
    42000,
    90000,
    60904,
    46000,
    85000,
    91000,
    150000,
    82000,
    96000,
    21300,
    8000,
    47000,
    53000,
    8000,
    55000,
    55000,
    245000,
    63000,
    40000,
    440000,
    40000,
    245000,
    35000,
    48700,
    58988,
    100000,
    35,
    38000,
    57000,
    41000,
    60000,
    65000,
    155000,
    52291,
    42000,
    70000,
    43000,
    65000,
    40000,
    24000,
    170164,
    5600000,
    42000,
    63000,
    43000,
    47254,
    95000,
    28000,
    47600,
    125000,
    80000,
    95000,
    67000,
    180000,
    17650,
    121000,
    43000,
    44518,
    130000,
    74000,
    31000,
    165000,
    43000,
    512000,
    90,
    36500,
    54250,
    100000,
    492000,
    90000,
    68123,
    60000,
    137000,
    36500,
    75000,
    1000,
    70200,
    95000,
    85000,
    1800,
    10000000,
    119.464,
    21500,
    3000,
    24000,
    40000,
    10602.41,
    60500,
    70000,
    20,
    70000,
    25000,
    100000,
    728,
    85000,
    110000,
    25000,
    60000,
    145000,
    65400,
    4000000,
    19000,
    75000,
    128000,
    56000,
    48000,
    80000,
    70000,
    40000,
    95000,
    4000,
    70000,
    6000,
    67000,
    70000,
    800,
    70000,
    68000,
    101391,
    11000,
    46000,
    120000,
    7650000,
    50000,
    38000,
    125000,
    7000,
    45000,
    22000,
    32000,
    140000,
    69000,
    700000,
    60000,
    90000,
    50000,
    95000,
    80000,
    24002,
    35000,
    69000,
    21000,
    69000,
    59830,
    18000,
    75000,
    48584.7,
    116000,
    85000,
    100000,
    250000,
    60240,
    100000,
    69900,
    61000,
    70236,
    146455,
    90000,
    25000,
    125000,
    83000,
    76000,
    180000,
    140000,
    78000,
    7500,
    43,
    100000,
    62000,
    5000000,
    30000,
    1600000,
    1150,
    732,
    110000,
    38000,
    2500000,
    32500,
    6000,
    108000,
    46574,
    130000,
    75000,
    125000,
    59700,
    40000,
    39,
    14000,
    42000,
    82000,
    45000,
    180000,
    140995,
    1800,
    123300,
    260000,
    82000,
    68000,
    31000,
    110000,
    78500,
    43000,
    150000,
    60000,
    46000,
    5,
    77710,
    100000,
    65000,
    37900,
    70000,
    750000,
    40000,
    24400,
    128500,
    81000,
    49000,
    1800000,
    66318.72,
    102000,
    95000,
    200000,
    70000,
    25300,
    300,
    140000,
    130000,
    40000,
    19192920202020,
    46000,
    75000,
    120000,
    600,
    165000,
    65000,
    12400,
    80000,
    66265,
    24000,
    180000,
    122000,
    5000,
    43184,
    67000,
    112000,
    5000,
    61220.4,
    16000,
    180000,
    110000,
    40000,
    50000,
    1780000,
    100000,
    96000,
    150000,
    160000,
    44000,
    82000,
    98000,
    15000,
    90000,
    4000,
    120000,
    1319,
    70000,
    90000,
    85000,
    10500,
    24000,
    52000,
    60000,
    41000,
    8000,
    69974,
    39000,
    1280000,
    120000,
    48000,
    99000,
    42000,
    52000,
    80000,
    128000,
    70000,
    59000,
    45000,
    42000,
    28800,
    50000,
    28800,
    45000,
    96000,
    141000,
    45000,
    144000,
    70000,
    18000,
    50000,
    4750,
    43000,
    132000,
    84000,
    40500,
    70000,
    17000,
    100000,
    28000,
    49475,
    60000,
    140000,
    140000,
    82000,
    69,
    26.5,
    74000,
    100000,
    35000,
    20000,
    33500,
    9000,
    47900,
    135000,
    44000,
    60000,
    10000,
    80000,
    9000,
    343000,
    2200,
    80000,
    11000000,
    54000,
    56000,
    45000,
    110000,
    58000,
    13000000,
    70000,
    15000,
    12000,
    120000,
    55000,
    44520,
    71000,
    4000,
    50000,
    98446,
    18700,
    27000,
    101520,
    65000,
    60000,
    75000,
    28000,
    74000,
    3990000,
    400000,
    110000,
    25000,
    17000,
    80000,
    10000,
    64000,
    95000,
    42000,
    16000,
    86000,
    100000,
    118000,
    180000,
    45000,
    64000,
    72000,
    190000,
    6000,
    70500,
    60000,
    894000,
    38000,
    32500,
    25000,
    79000,
    21600,
    14000,
    214500,
    2300000,
    35000,
    10500,
    75000,
    50000,
    45705,
    55400,
    62000,
    110000,
    42000,
    47000,
    78000,
    68000,
    300000,
    79800,
    60000,
    4360000,
    51480,
    52000,
    19500,
    83000,
    90000,
    65000,
    123840,
    79180,
    146000,
    2650,
    100000,
    58800,
    92000,
    290000,
    67500,
    216000,
    100000,
    131.92,
    73000,
    80000,
    80000,
    29000,
    49000,
    50,
    150000,
    152000,
    82000,
    155000,
    42950,
    109000,
    31000,
    110000,
    50000,
    35000,
    50000,
    80000,
    57000,
    55000,
    152000,
    30000,
    72000,
    80000,
    39714.98,
    4800000,
    105000,
    100,
    84000,
    117000,
    184000,
    160000,
    181910,
    105000,
    55000,
    85000,
    53463,
    185000,
    8250000,
    234000,
    73000,
    206000,
    2200000,
    88558,
    125000,
    170000,
    82000,
    67000,
    18705,
    42000,
    126000,
    135000,
    120000,
    120000,
    3000,
    75000,
    95000,
    45000,
    78750,
    53000,
    52493,
    112000,
    95000,
    55000,
    120000,
    3000,
    25000,
    3000000,
    53000,
    283000,
    45000,
    400000,
    61870,
    700,
    35000,
    60000,
    48900,
    12000,
    50000,
    108000,
    78000,
    72000,
    180000,
    30000,
    220000,
    1200,
    75000,
    6400,
    180000,
    80000,
    45000,
    5000,
    39437,
    140000,
    80000,
    95000,
    50000,
    62000,
    135000,
    28857,
    73000,
    45000,
    28857,
    43359,
    103000,
    85789,
    66000,
    154000,
    60000,
    60000,
    42000,
    80000,
    150000,
    98600,
    132000,
    43000,
    43000,
    130000,
    131300,
    106000,
    13800,
    90000,
    5060,
    77098,
    140000,
    43000,
    140000,
    38000,
    84000,
    90000,
    330000,
    18000,
    80000,
    93400.92,
    49336,
    86000,
    70000,
    250000,
    84000,
    140000,
    70000,
    120000,
    730,
    27500,
    77000,
    71760,
    85000,
    150000,
    60000,
    250000,
    50000,
    43500,
    73000,
    96000,
    27000,
    42000,
    182000,
    80000,
    100000,
    16000,
    51000,
    88000,
    147000,
    65000,
    68000,
    125000,
    90000,
    102000,
    70000,
    135000,
    34200,
    160000,
    55000,
    65000,
    48232,
    35000,
    125000,
    11292,
    750,
    15600,
    125000,
    92000,
    3318,
    45000,
    26000,
    15,
    64000,
    70000,
    310000,
    100000,
    50000,
    24600,
    100000,
    240000,
    165000,
    85000,
    65000,
    36000,
    25000,
    30000,
    70000,
    105000,
    51,
    55000,
    39000,
    7000,
    225000,
    24000,
    250000,
    30000,
    40000,
    189000,
    68000,
    8500,
    89000,
    50000,
    70000,
    170000,
    78000,
    48582,
    55720,
    24000,
    77000,
    46000,
    80000,
    200000,
    123828,
    47000,
    168,
    133700,
    100000,
    155700,
    69576,
    590000,
    190000,
    130000,
    45000,
    4000000,
    42000,
    140000,
    103000,
    65000,
    55905,
    40,
    82062,
    35000,
    23000,
    35000,
    50000,
    160000,
    52773,
    60000,
    109000,
    87091.64,
    178000,
    113000,
    181000,
    120000,
    210000,
    69743,
    154000,
    62000,
    16000,
    6134000,
    71000,
    220000,
    69000,
    62000,
    145000,
    78000,
    54000,
    41000,
    2994865,
    122000,
    65000,
    900000,
    44500,
    80000,
    150000,
    360000,
    400000,
    25000,
    210000,
    125444,
    95000,
    135000,
    410000,
    45000,
    60000,
    56000,
    108000,
    71000,
    54501.76,
    210000,
    120771,
    135880,
    650000,
    55000,
    105000,
    99345,
    115000,
    66000,
    350000,
    1730187,
    145000,
    67000,
    140000,
    60000,
    92000,
    135000,
    1250000,
    77.2,
    150000,
    211235,
    165000,
    86958,
    160000,
    61000,
    80000,
    130000,
    102409,
    140000,
    101200,
    44000,
    27000,
    170000,
    31000,
    37500,
    50000,
    164000,
    44480,
    81000,
    150000,
    65000,
    1,
    170000,
    147150,
    52.279,
    200000,
    65,
    135000,
    85471,
    86359,
    80000,
    164462,
    69000,
    200000,
    60458,
    165000,
    48905,
    49500,
    70000,
    140000,
    230000,
    80000,
    80000,
    88552,
    85.1,
    83000,
    2000,
    100000,
    70000,
    450000,
    250000,
    120000,
    225000,
    137000,
    195000,
    154000,
    1851000,
    75000,
    160000,
    40000,
    48000,
    49000,
    75000,
    89000,
    100000,
    175000,
    67000,
    82500,
    70000,
    160000,
    40000,
    480000,
    79500,
    114000,
    20000,
    10000,
    210000,
    210000,
    108000,
    110000,
    110000,
    74000,
    213,
    100000,
    120000,
    84800,
    99000,
    100000,
    230000,
    69907,
    60000,
    31000,
    94000,
    145000,
    42000,
    72500,
    198000,
    140000,
    107486,
    700000,
    112000,
    75000,
    75000,
    63500,
    100000,
    143000,
    245000,
    50000,
    45000,
    58212,
    140000,
    130000,
    145000,
    240000,
    74000,
    85000,
    100000,
    40000,
    73500,
    101000,
    540000,
    210830,
    105000,
    200000,
    210830,
    210830,
    50000,
    35000,
    120000,
    180000,
    43000,
    150000,
    55000,
    30,
    3300000,
    107000,
    175000,
    90825,
    47000,
    52000,
    128000,
    120000,
    220000,
    424000,
    45560,
    120000,
    66200,
    75000,
    160000,
    135000,
    108000,
    68000,
    151000,
    54000,
    1,
    45000,
    115000,
    950000,
    136000,
    1200000,
    110000,
    64000,
    175000,
    109000,
    55000,
    120000,
    411000,
    117000,
    85000,
    94,
    60000,
    65000,
    50310,
    179000,
    135000,
    40000,
    146000,
    47000,
    51000,
    140000,
    60000,
    160000,
    30000,
    124000,
    7000,
    240000,
    38000,
    330000,
    69000,
    500000,
    100000,
    85000,
    30000,
    65000,
    110000,
    105000,
    52000,
    130000,
    120000,
    400000,
    121000,
    148000,
    69000,
    50000,
    46200,
    42000,
    60000,
    260000,
    55000,
    120000,
    380000,
    22000,
    45000,
    46000,
    50000,
    19925,
    86500,
    65000,
    57200,
    75000,
    65000,
    80000,
    67514,
    95000,
    51000,
    130000,
    130000,
    100000,
    100,
    170000,
    150000,
    79101,
    210000,
    75000,
    60000,
    70240,
    175000,
    118000,
    350000,
    210000,
    61000,
    100000,
    350000,
    160000,
    145000,
    64433,
    260000,
    230000,
    1600000,
    100000,
    168000,
    130000,
    145000,
    48.756,
    70361,
    73493.98,
    125000,
    1100,
    125000,
    98990,
    62000,
    100000,
    480000,
    38000,
    72000,
    37.83,
    149000,
    53000,
    95000,
    285,
    20000,
    10000,
    65000,
    90000,
    87741,
    320000,
    52205,
    200000,
    140000,
    100000,
    220000,
    200000,
    60000,
    54000,
    233000,
    40000,
    175000,
    123400,
    5500000,
    105000,
    93000,
    70000,
    48000,
    125000,
    72500,
    121500,
    197282,
    130000,
    11000,
    170000,
    17.3,
    75000,
    2000,
    147000,
    150000,
    210000,
    140000,
    105800,
    60000,
    198000,
    170000,
    93000,
    3000000,
    140000,
    75000,
    40903,
    26000,
    166000,
    150000,
    100000,
    182000,
    135.473,
    200000,
    63000,
    150000,
    120000,
    48000,
    530000,
    65000,
    93975.9,
    46300,
    140000,
    200000,
    52000,
    81378,
    160000,
    700000,
    77963,
    36000,
    110000,
    75000,
    78,
    90000,
    110000,
    113000,
    165000,
    330000,
    105000,
    60000,
    110000,
    68000,
    250000,
    65000,
    100000,
    152000,
    253000,
    64100,
    986840,
    72000,
    150000,
    38000,
    65576,
    22000,
    190000,
    109000,
    103971.38,
    310000,
    150000,
    150000,
    100000,
    68900,
    250000,
    50000,
    260000,
    75000,
    95000,
    200000,
    65000,
    132000,
    200000,
    55000,
    82000,
    2000000,
    180000,
    200000,
    68000,
    150000,
    68494,
    88,
    11000,
    60000,
    240000,
    45000,
    370000,
    140000,
    62000,
    72300,
    160,
    77000,
    44700,
    47000,
    220000,
    220,
    150000,
    81855.45,
    180000,
    400000,
    185000,
    100000,
    194000,
    135000,
    163000,
    115000,
    137000,
    163000,
    104000,
    200000,
    39500,
    750000,
    253000,
    540000,
    160000,
    190000,
    75000,
    186000,
    45000,
    269000,
    166661,
    181000,
    80000,
    53000,
    82236,
    61000,
    76000,
    75000,
    56000,
    20000,
    97346,
    210000,
    105000,
    100,
    33000,
    150000,
    90000,
    35000,
    40000,
    220000,
    40000,
    81000,
    220000,
    95000,
    180000,
    50000,
    66000,
    91410,
    300000,
    126,
    107000,
    1500,
    50000,
    83000,
    20300,
    1,
    88000,
    125000,
    126000,
    40500,
    85000,
    70700,
    161000,
    88000,
    260000,
    70000,
    40000,
    42000,
    139000,
    78900,
    282000,
    60000,
    120000,
    50000,
    20000,
    55000,
    140000,
    160000,
    51000,
    50000,
    3500,
    108000,
    92000,
    75000,
    88000,
    30000,
    120000,
    50000,
    30000,
    90000,
    99500,
    120000,
    5000,
    44000,
    62490,
    90000,
    130000,
    1850,
    61000,
    180000,
    900000,
    85800,
    62000,
    63000,
    107,
    113000,
    271802,
    50847,
    36682,
    65000,
    272000,
    2500,
    150000,
    136000,
    104000,
    95000,
    107106,
    65000,
    100000,
    415000,
    56000,
    176304,
    34000,
    92000,
    40000,
    60000,
    180000,
    92000,
    1000,
    96000,
    100000,
    180000,
    165000,
    100000,
    62000,
    59000,
    125000,
    120000,
    180000,
    40000,
    126000,
    37900,
    41000,
    85000,
    120000,
    120000,
    360000,
    33000,
    1500,
    390000,
    220000,
    8000000,
    8000000,
    120000,
    82000,
    221248,
    63500,
    130000,
    206000,
    40000,
    400000,
    124000,
    154800,
    163000,
    40000,
    251000,
    320850,
    22000,
    100000,
    450000,
    155000,
    120000,
    180000,
    133360,
    79889,
    240000,
    158000,
    42000,
    70000,
    72660,
    57000,
    100000,
    104000,
    66000,
    171495,
    250000,
    68000,
    60000,
    130000,
    38500,
    55000,
    122612,
    102000,
    55000,
    60000,
    85000,
    200000,
    85000,
    85000,
    170000,
    160000,
    70000,
    72000,
    72000,
    150000,
    149500,
    130000,
    2000000,
    126500,
    200000,
    33000,
    135000,
    50000,
    47000,
    96000,
    188000,
    120000,
    50000,
    80000,
    12000,
    105000,
    70000,
    130000,
    30000,
    120000,
    100000,
    40000000,
    110000,
    580000,
    1,
    20000,
    140000,
    90000,
    99000,
    14500,
    64800,
    120000,
    150000,
    69000,
    180000,
    99000,
    85000,
    47250,
    86000,
    85000,
]
print("La mediana de los sueldos de Openqube Feb 2020: ",np.median(Array_Sueldos_Openqube_Feb_2020))
print("El sueldo promedio de los sueldos de Openqube Feb 2020: ",np.mean(Array_Sueldos_Openqube_Feb_2020))

La mediana de los sueldos de Openqube Feb 2020:  95000.0
El sueldo promedio de los sueldos de Openqube Feb 2020:  2992143846.202422
